# Generated by Django 4.1.2 on 2022-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_titulo', models.CharField(max_length=120)),
                ('libro_descripcion_breve', models.CharField(max_length=200)),
                ('libro_imagen', models.CharField(max_length=120)),
                ('libro_nuevo', models.BooleanField()),
                ('libro_leyendo', models.BooleanField()),
                ('libro_numero_id', models.IntegerField()),
                ('libro_sinopsis_breve', models.TextField()),
                ('libro_fecha_publicacion', models.DateField()),
                ('libro_autor', models.CharField(max_length=150)),
                ('libro_genero', models.CharField(max_length=150)),
                ('libro_formato', models.CharField(max_length=150)),
                ('libro_critica_breve', models.CharField(max_length=400)),
                ('libro_critica_fuente', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_libros_relacionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_relacionado_titulo', models.CharField(max_length=200)),
                ('libro_relacionado_imagen', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=120)),
                ('usuario_critica_libro', models.TextField()),
                ('usuario_puntuacion_libro', models.IntegerField()),
            ],
        ),
    ]
