# Generated by Django 4.1.1 on 2022-11-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_virtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='resenia',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=500)),
                ('puntuacion', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_virtual.libro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_virtual.usuario')),
            ],
        ),
    ]
