# Generated by Django 4.1.1 on 2022-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_virtual', '0002_alter_resenia_resenia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
